//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepRancher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoisyClient {
            get {
                return ((bool)(this["NoisyClient"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\Temp\\RepRancher\\Error.txt")]
        public string ErrorFile {
            get {
                return ((string)(this["ErrorFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S3cretKeyP4ssword")]
        public string MakerFarmClientAPIKey {
            get {
                return ((string)(this["MakerFarmClientAPIKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MakerFarmClientID {
            get {
                return ((int)(this["MakerFarmClientID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MakerFarmTime {
            get {
                return ((int)(this["MakerFarmTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lothar.architecture.yale.edu:50614/odata/")]
        public string MakerFarmAPIUri {
            get {
                return ((string)(this["MakerFarmAPIUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MakerFarmClientEnable {
            get {
                return ((bool)(this["MakerFarmClientEnable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ErrorTimer {
            get {
                return ((int)(this["ErrorTimer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          <ArrayOfRancherBrand xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xml" +
            "ns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n          <RancherBrand>\r\n " +
            "           <Enabled>true</Enabled>\r\n            <Type>Conveyor_2_4_1</Type>\r\n   " +
            "         <PrintTemporaryFileStoragePath>C:\\Windows\\Temp\\_2_4_1_Client\\</PrintTem" +
            "poraryFileStoragePath>\r\n            <PrinterReplyTimeout>5</PrinterReplyTimeout>" +
            "\r\n            <IPAddress>127.0.0.1</IPAddress>\r\n            <PortNumber>9999</Po" +
            "rtNumber>\r\n            <AdvancedConfigurationString>test</AdvancedConfigurationS" +
            "tring>\r\n          </RancherBrand>\r\n          <RancherBrand>\r\n            <Enable" +
            "d>false</Enabled>\r\n            <Type>Conveyor_3_0_0</Type>\r\n            <PrintTe" +
            "mporaryFileStoragePath>C:\\Windows\\Temp\\_3_0_0_Client\\</PrintTemporaryFileStorage" +
            "Path>\r\n            <PrinterReplyTimeout>5</PrinterReplyTimeout>\r\n            <IP" +
            "Address>127.0.0.1</IPAddress>\r\n            <PortNumber>9999</PortNumber>\r\n      " +
            "      <AdvancedConfigurationString>Invalid</AdvancedConfigurationString>\r\n      " +
            "    </RancherBrand>\r\n          <RancherBrand>\r\n            <Enabled>false</Enabl" +
            "ed>\r\n            <Type>DimensionSST768</Type>\r\n            <PrintTemporaryFileSt" +
            "oragePath>C:\\Windows\\Temp\\Dimension_Client</PrintTemporaryFileStoragePath>\r\n    " +
            "        <PrinterReplyTimeout>5</PrinterReplyTimeout>\r\n            <IPAddress>127" +
            ".0.0.1</IPAddress>\r\n            <PortNumber>5054</PortNumber>\r\n            <Adva" +
            "ncedConfigurationString>Invalid</AdvancedConfigurationString>\r\n          </Ranch" +
            "erBrand>\r\n          </ArrayOfRancherBrand>\r\n        ")]
        public global::RepRancher.RancherBrandCollection RancherBrands {
            get {
                return ((global::RepRancher.RancherBrandCollection)(this["RancherBrands"]));
            }
        }
    }
}
