{"id":2,"jsonrpc":"2.0","method":"getprinters","params":[]}


{"jsonrpc": "2.0", "result": [{"can_print": true, "number_of_toolheads": 1, "has_heated_platform": false, "display_name": "Kylie", "name": {"iserial": "75237333536351713081", "pid": 45077, "port_type": "UsbPort", "vid": 9153}, "printer_type": "The Replicator 2", "profile_name": "Replicator2", "toolhead_target_temperature": null, "build_volume": [285, 153, 155], "state": "IDLE", "driver_name": "s3g", "machine_names": ["TheReplicator2"], "firmware_version": [7, 5], "temperature": null}, {"can_print": false, "has_heated_platform": true, "toolhead_target_temperature": null, "machine_names": ["TheReplicator2X"], "printer_type": "The Replicator 2X", "firmware_version": null, "temperature": null, "number_of_toolheads": 2, "display_name": "The Replicator 2X", "name": "The Replicator 2X", "profile_name": "Replicator2X", "build_volume": [246, 152, 155], "state": "DISCONNECTED", "driver_name": "s3g"}, {"can_print": false, "has_heated_platform": true, "toolhead_target_temperature": null, "machine_names": ["TheReplicator"], "printer_type": "The Replicator Dual", "firmware_version": null, "temperature": null, "number_of_toolheads": 2, "display_name": "The Replicator Dual", "name": "The Replicator Dual", "profile_name": "ReplicatorDual", "build_volume": [225, 145, 150], "state": "DISCONNECTED", "driver_name": "s3g"}, {"can_print": false, "has_heated_platform": false, "toolhead_target_temperature": null, "machine_names": ["TheReplicator2"], "printer_type": "The Replicator 2", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "The Replicator 2", "name": "The Replicator 2", "profile_name": "Replicator2", "build_volume": [285, 153, 155], "state": "DISCONNECTED", "driver_name": "s3g"}, {"can_print": false, "has_heated_platform": true, "toolhead_target_temperature": null, "machine_names": ["TheReplicator"], "printer_type": "The Replicator Single", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "The Replicator Single", "name": "The Replicator Single", "profile_name": "ReplicatorSingle", "build_volume": [225, 145, 150], "state": "DISCONNECTED", "driver_name": "s3g"}, {"can_print": false, "has_heated_platform": true, "toolhead_target_temperature": null, "machine_names": ["Thing-O-Matic", "TOM"], "printer_type": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", "name": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", "profile_name": "TOMStepstruderSingle", "build_volume": [106, 120, 106], "state": "DISCONNECTED", "driver_name": "s3g"}, {"can_print": false, "has_heated_platform": false, "toolhead_target_temperature": null, "machine_names": ["Tinkerbell"], "printer_type": "Tinkerbell", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "Tinkerbell", "name": "Tinkerbell", "profile_name": "Tinkerbell", "build_volume": [100, 100, 125], "state": "DISCONNECTED", "driver_name": "birdwing"}, {"can_print": false, "has_heated_platform": true, "toolhead_target_temperature": null, "machine_names": ["Moose"], "printer_type": "Moose", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "Moose", "name": "Moose", "profile_name": "Moose", "build_volume": [305, 305, 457], "state": "DISCONNECTED", "driver_name": "birdwing"}, {"can_print": false, "has_heated_platform": false, "toolhead_target_temperature": null, "machine_names": ["Platypus"], "printer_type": "Platypus", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "Platypus", "name": "Platypus", "profile_name": "Platypus", "build_volume": [252, 199, 150], "state": "DISCONNECTED", "driver_name": "birdwing"}], "id": 2}

{
    "jsonrpc": "2.0", "result": [
    {
        "can_print": true, 
        "number_of_toolheads": 1, 
        "has_heated_platform": false, 
        "display_name": "Kylie", 
        "name": 
            {
            "iserial": "75237333536351713081", 
            "pid": 45077, 
            "port_type": "UsbPort", 
            "vid": 9153
            }, 
        "printer_type": "The Replicator 2", 
        "profile_name": "Replicator2", 
        "toolhead_target_temperature": null, 
        "build_volume": [285, 153, 155], 
        "state": "IDLE", "driver_name": "s3g", 
        "machine_names": ["TheReplicator2"], 
        "firmware_version": [7, 5], 
        "temperature": null
    }, 
    {
        "can_print": false, 
        "has_heated_platform": true, 
        "toolhead_target_temperature": null, 
        "machine_names": ["TheReplicator2X"], 
        "printer_type": "The Replicator 2X", 
        "firmware_version": null, 
        "temperature": null, 
        "number_of_toolheads": 2, 
        "display_name": "The Replicator 2X", 
        "name": "The Replicator 2X", 
        "profile_name": "Replicator2X", 
        "build_volume": [246, 152, 155], 
        "state": "DISCONNECTED", 
        "driver_name": "s3g"
    }, 
    {
        "can_print": false, 
        "has_heated_platform": true, 
        "toolhead_target_temperature": null, 
        "machine_names": ["TheReplicator"], 
        "printer_type": "The Replicator Dual", 
        "firmware_version": null, 
        "temperature": null, 
        "number_of_toolheads": 2, 
        "display_name": "The Replicator Dual", 
        "name": "The Replicator Dual", 
        "profile_name": "ReplicatorDual", 
        "build_volume": [225, 145, 150], 
        "state": "DISCONNECTED", 
        "driver_name": "s3g"
    }, 
    {
        "can_print": false, 
        "has_heated_platform": false, 
        "toolhead_target_temperature": null, 
        "machine_names": ["TheReplicator2"], 
        "printer_type": "The Replicator 2", 
        "firmware_version": null, 
        "temperature": null, 
        "number_of_toolheads": 1, 
        "display_name": "The Replicator 2", 
        "name": "The Replicator 2", 
        "profile_name": "Replicator2", 
        "build_volume": [285, 153, 155], 
        "state": "DISCONNECTED", 
        "driver_name": "s3g"
    }, 
    {
        "can_print": false, 
        "has_heated_platform": true, 
        "toolhead_target_temperature": null, 
        "machine_names": ["TheReplicator"], 
        "printer_type": "The Replicator Single", 
        "firmware_version": null, 
        "temperature": null, 
        "number_of_toolheads": 1, 
        "display_name": "The Replicator Single", 
        "name": "The Replicator Single", 
        "profile_name": "ReplicatorSingle", 
        "build_volume": [225, 145, 150], 
        "state": "DISCONNECTED", 
        "driver_name": "s3g"
    }, 
    {
        "can_print": false, 
        "has_heated_platform": true, 
        "toolhead_target_temperature": null, 
        "machine_names": ["Thing-O-Matic", "TOM"], 
        "printer_type": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", 
        "firmware_version": null, 
        "temperature": null, 
        "number_of_toolheads": 1, 
        "display_name": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", 
        "name": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", 
        "profile_name": "TOMStepstruderSingle", 
        "build_volume": [106, 120, 106], 
        "state": "DISCONNECTED", "driver_name": "s3g"
    }, 
    {
        "can_print": false, 
        "has_heated_platform": false, 
        "toolhead_target_temperature": null, 
        "machine_names": ["Tinkerbell"], 
        "printer_type": "Tinkerbell", 
        "firmware_version": null, 
        "temperature": null, 
        "number_of_toolheads": 1, 
        "display_name": "Tinkerbell", 
        "name": "Tinkerbell", 
        "profile_name": "Tinkerbell", 
        "build_volume": [100, 100, 125], 
        "state": "DISCONNECTED", 
        "driver_name": "birdwing"
    }, 
    {
        "can_print": false, 
        "has_heated_platform": true, 
        "toolhead_target_temperature": null, 
        "machine_names": ["Moose"], 
        "printer_type": "Moose", 
        "firmware_version": null, 
        "temperature": null, 
        "number_of_toolheads": 1, 
        "display_name": "Moose", "name": "Moose", 
        "profile_name": "Moose", 
        "build_volume": [305, 305, 457], 
        "state": "DISCONNECTED", 
        "driver_name": "birdwing"
    }, 
    {
        "can_print": false, 
        "has_heated_platform": false, 
        "toolhead_target_temperature": null, 
        "machine_names": ["Platypus"], 
        "printer_type": "Platypus", 
        "firmware_version": null, 
        "temperature": null, 
        "number_of_toolheads": 1, 
        "display_name": "Platypus", 
        "name": "Platypus", 
        "profile_name": "Platypus", 
        "build_volume": [252, 199, 150], 
        "state": "DISCONNECTED", 
        "driver_name": "birdwing"
    }],
    "id": 2}
