{
    "jsonrpc": "2.0", 
    "result": [
        {
            "displayName": "The Replicator 2", 
            "name": "23C1:B016:55330343434351C0D191", 
            "printerType": "The Replicator 2", 
            "profile_name": "Replicator2", 
            "hasHeatedPlatform": false, 
            "toolhead_target_temperature": [230], 
            "build_volume": [285, 153, 155], 
            "state": "OPERATION", 
            "driver_name": "s3g", 
            "port_name": "COM8:9153:45078", 
            "temperature": {
                "heated_platforms": [], 
                "tools": {"0": 225}}, 
            "uniqueName": "23C1:B016:55330343434351C0D191", 
            "canPrintToFile": true, 
            "machineNames": ["TheReplicator2"], 
            "numberOfToolheads": 1, 
            "firmware_version": 705, 
            "canPrint": true}, 
        {
            "displayName": "The Replicator 2X", 
            "name": "The Replicator 2X", 
            "printerType": "The Replicator 2X", 
            "profile_name": "Replicator2X", 
            "hasHeatedPlatform": true, 
            "toolhead_target_temperature": null, 
            "build_volume": [246, 152, 155], 
            "state": "DISCONNECTED", 
            "driver_name": "s3g", 
            "port_name": null, 
            "temperature": {
                "heated_platforms": {}, 
                "tools": {}}, 
            "uniqueName": "The Replicator 2X", 
            "canPrintToFile": null, 
            "machineNames": ["TheReplicator2X"], 
            "numberOfToolheads": 2, 
            "firmware_version": null, 
            "canPrint": false}, 
        {
            "displayName": "The Replicator Dual", 
            "name": "The Replicator Dual", 
            "printerType": "The Replicator Dual", 
            "profile_name": "ReplicatorDual", 
            "hasHeatedPlatform": true, 
            "toolhead_target_temperature": null, 
            "build_volume": [225, 145, 150], 
            "state": "DISCONNECTED", 
            "driver_name": "s3g", 
            "port_name": null, 
            "temperature": {
                "heated_platforms": {}, 
                "tools": {}}, 
            "uniqueName": "The Replicator Dual", 
            "canPrintToFile": null, 
            "machineNames": ["TheReplicator"], 
            "numberOfToolheads": 2, 
            "firmware_version": null, 
            "canPrint": false}, 
        {
            "displayName": "The Replicator 2", 
            "name": "The Replicator 2", 
            "printerType": "The Replicator 2", 
            "profile_name": "Replicator2", 
            "hasHeatedPlatform": false, 
            "toolhead_target_temperature": null, 
            "build_volume": [285, 153, 155], 
            "state": "DISCONNECTED", 
            "driver_name": "s3g", 
            "port_name": null, 
            "temperature": {
                "heated_platforms": {}, 
                "tools": {}}, 
            "uniqueName": "The Replicator 2", 
            "canPrintToFile": null, 
            "machineNames": ["TheReplicator2"], 
            "numberOfToolheads": 1, 
            "firmware_version": null, 
            "canPrint": false}, 
        {
            "displayName": "The Replicator Single", 
            "name": "The Replicator Single", 
            "printerType": "The Replicator Single", 
            "profile_name": "ReplicatorSingle", 
            "hasHeatedPlatform": true, 
            "toolhead_target_temperature": null, 
            "build_volume": [225, 145, 150], 
            "state": "DISCONNECTED", 
            "driver_name": "s3g", 
            "port_name": null, 
            "temperature": {
                "heated_platforms": {}, 
                "tools": {}}, 
            "uniqueName": "The Replicator Single", 
            "canPrintToFile": null, 
            "machineNames": ["TheReplicator"], 
            "numberOfToolheads": 1,
            "firmware_version": null, 
            "canPrint": false}, 
        {
            "displayName": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", 
            "name": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", 
            "printerType": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", 
            "profile_name": "TOMStepstruderSingle", 
            "hasHeatedPlatform": true, 
            "toolhead_target_temperature": null, 
            "build_volume": [106, 120, 106], 
            "state": "DISCONNECTED", 
            "driver_name": "s3g", 
            "port_name": null, 
            "temperature": {
                "heated_platforms": {}, 
                "tools": {}}, 
            "uniqueName": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", 
            "canPrintToFile": null, 
            "machineNames": ["Thing-O-Matic", "TOM"], 
            "numberOfToolheads": 1, 
            "firmware_version": null, 
            "canPrint": false}], 
    "id": "9000"}
