{"id":0,"jsonrpc":"2.0","method":"hello","params":{"username":"Rob"}}

{"jsonrpc": "2.0", "result": "world", "id": 0}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 24, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"id":1,"jsonrpc":"2.0","method":"getports","params":{}}

{"jsonrpc": "2.0", "result": [{"driver_profiles": {"birdwing": ["Platypus"]}, "machine_hash": "23C1:0005:23C100053C7059002409", "machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "port_type": "UsbPort", "machine_type": "Platypus"}], "id": 1}
{"id":2,"jsonrpc":"2.0","method":"getprinters","params":{}}

{"jsonrpc": "2.0", "result": [{"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 24, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, {"can_print": false, "has_heated_platform": true, "toolhead_target_temperature": null, "profile_name": "Replicator2X", "printer_type": "The Replicator 2X", "firmware_version": n
ull, "temperature": null, "number_of_toolheads": 2, "display_name": "The Replicator 2X", "name": "The Replicator 2X", "build_volume": [246, 152, 155], "state": "DISCONNECTED", "driver_name": "s3g"}, {"can_print": false, "has_heated_platform": true, "toolhead_target_temperature": null, "profile_name": "ReplicatorDual", "printer_type": "The Replicator Dual", "firmware_version": null, "temperature": null, "number_of_toolheads": 2, "dis
play_name": "The Replicator Dual", "name": "The Replicator Dual", "build_volume": [225, 145, 150], "state": "DISCONNECTED", "driver_name": "s3g"}, {"can_print": false, "has_heated_platform": false, "toolhead_target_temperature": null, "profile_name": "Replicator2", "printer_type": "The Replicator 2", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "The Replicator 2", "name": "The Replicator 2", "build_volume": [285, 153, 155], "state": "DISCONNECTED", "driver_name": "s3g"}, {"can_print": false, "has_heated_platform": true, "toolhead_target_temperature": null, "profile_name": "ReplicatorSingle", "printer_type": "The Replicator Single", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "The Replicator Single", "name": "The Replicator Single", "build_volume": [225, 145, 150], "state": "DISCONNECTED", "driver_name": "s3g"}, {"can_print": false, "has_heated_platform": true, "toolhead_target_temperature": null, "profile_name": "TOMSteps
truderSingle", "printer_type": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", "name": "Thing-O-Matic Single, Stepstruder Mk6 or Mk7", "build_volume": [106, 120, 106], "state": "DISCONNECTED", "driver_name": "s3g"}, {"can_print": false, "has_heated_platform": false, "toolhead_target_temperature": n
ull, "profile_name": "Tinkerbell", "printer_type": "Tinkerbell", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "Tinkerbell", "name": "Tinkerbell", "build_volume": [100, 100, 125], "state": "DISCONNECTED", "driver_name": "birdwing"}, {"can_print": false, "has_heated_platform": true, "toolhead_target_temperature": null, "profile_name": "Moose", "printer_type": "Moose", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "Moose", "name": "Moose", "build_volume": [300, 305, 457], "state": "DISCONNECTED", "driver_name": "birdwing"}, {"can_print": false, "has_heated_platform": false, "toolhead_target_temperature": null, "profile_name": "Platypus", "printer_type": "Platypus", "firmware_version": null, "temperature": null, "number_of_toolheads": 1, "display_name": "Platypus", "name": "Platypus", "build_volume": [252, 199, 150], "state": "DISCONNECTED", "driver_name": "birdwing"}], "id": 2}
{"id":3,"jsonrpc":"2.0","method":"getjobs","params":{}}

{"jsonrpc": "2.0", "result": [], "id": 3}
{"id":4,"jsonrpc":"2.0","method":"connect_to_machine","params":{"machine_name":"23C1:0005:23C100053C7059002409"}}

{"jsonrpc": "2.0", "result": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 24, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "id": 4}
{"id":5,"jsonrpc":"2.0","method":"send_thingiverse_credentials","params":{"birdwing_code":"","client_secret":"{65a1922e-e467-4ffd-9ee2-668423460b6f}","machine_name":"23C1:0005:23C100053C7059002409","thingiverse_token":"837bfb02fa5039bc1feba50b57d30ec1","username":"RobListon"}}

{"jsonrpc": "2.0", "result": null, "id": 5}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 23, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
