{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 24, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 23, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 24, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 23, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"id":6,"jsonrpc":"2.0","method":"request_camera_stream","params":{"machine_name":"23C1:0005:23C100053C7059002409","path":"C:/Users/Rob/AppData/Local/Temp/MakerWare-l9Mfi9"}}

{"jsonrpc": "2.0", "result": true, "id": 6}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpoqe8n7"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmppsvhxy"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpkfmfi_"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpxxnxk6"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp9qyw3s"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpjwwyqu"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpzhmlez"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpvrzeeh"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpq4fvh_"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp8d4qj8"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmph3wrxn"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpkmmhar"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpegeuzs"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpphmrkr"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpapgok8"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpt4dqlc"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpshcf_s"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpieubex"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpn_ny4v"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpe6iagt"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpqcrmvt"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpb1sdpz"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmprg6nby"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmplcclh5"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpibkkm8"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpqkbquk"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpv4r1uo"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpv1ni20"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpi3ekln"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmphvhi5b"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpcm83tl"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp9szjvg"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpz2yh3a"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 24, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpmmbgdc"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp_5yxc1"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 23, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpyqwhsp"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmps3odtm"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmprjiaqz"}, "jsonrpc": "2.0", "method": "camera_frame"}
