{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp5wdsoj"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp7g21ac"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp4n8b6c"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp8ao2yk"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpcojk8h"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpi4q5_q"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 24, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpr1yzhr"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpiixexz"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"id":7,"jsonrpc":"2.0","method":"print_from_file","params":{"input_file":"C:/Users/Rob/AppData/Local/Temp/MakerWare-GN2aKw/1 inch cube.makerbot","machine_name":"23C1:0005:23C100053C7059002409"}}

{"jsonrpc": "2.0", "result": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": false, "failure": null, "process_id": null, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "state": "RUNNING", "driver_name": "birdwing", "progress": null, "type": "PrintFromFileJob", "conclusion": null}, "id": 7}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": false, "failure": null, "process_id": null, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "state": "RUNNING", "driver_name": "birdwing", "progress": null, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobadded"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": null, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "state": "RUNNING", "driver_name": "birdwing", "progress": null, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp6nnqxb"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": null, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "state": "RUNNING", "driver_name": "birdwing", "progress": {"progress": 23.027730537323084, "name": "put"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 23, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": null, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "state": "RUNNING", "driver_name": "birdwing", "progress": {"progress": 46.05546107464617, "name": "put"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": null, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "state": "RUNNING", "driver_name": "birdwing", "progress": {"progress": 69.08319161196924, "name": "put"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": null, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "state": "RUNNING", "driver_name": "birdwing", "progress": {"progress": 92.11092214929234, "name": "put"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": null, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "state": "RUNNING", "driver_name": "birdwing", "progress": {"progress": 100.0, "name": "put"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 23, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"username": "RobListon", "print_temperatures": {}, "complete": false, "filepath": null, "cancellable": true, "start_time": null, "thing_id": null, "step": "initializing", "name": "PrintProcess", "elapsed_time": 0, "filament_extruded": 0, "reason": null, "error": null, "cancelled": false, "progress": 0, "can_print_again": false, "id": 36, "methods": []}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disa
bled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 23, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"username": "RobListon", "print_temperatures": {}, "complete": false, "filepath": null, "cancellable": true, "start_time": null, "thing_id": null, "step": "initializing", "name": "PrintProcess", "elapsed_time": 0, "filament_extruded": 0, "reason": null, "error": null, "cancelled": false, "progress": 0, "can_print_again": false, "id": 36, "methods": []}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disa
bled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": null, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "progress": {"progress": 100.0, "name": "put"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "progress": {"progress": 0, "name": "initializing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpxkmaf8"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 23, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 0, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": true,
 "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "api
_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 0, "name": "initializing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 0, "name": "initializing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 0, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpkdlj8m"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 23, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 1, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": true
, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "ap
i_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 1, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpgvdhmc"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpwhlnin"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp8hxe0m"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp1d8a_f"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp_hvawy"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpvwigpc"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpvl3smw"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 24, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 2, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": true
, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "ap
i_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 2, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpatsnfo"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpi0nxhv"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpnjufku"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 25, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 3, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": true
, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "ap
i_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 3, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpu5svdj"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpteijbs"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp5x_5mm"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 26, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 3, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": true
, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "ap
i_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 3, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmplm1sf4"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpc3eowa"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpqyvfwu"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 28, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 5, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": true
, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "ap
i_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 5, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpemrb9l"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp2f1apd"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpeesnam"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 29, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 5, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": true
, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "ap
i_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 5, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp2shah3"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpxevdfu"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpzfkqld"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 31, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 6, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": true
, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "ap
i_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 6, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpqrbp3n"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpuw8mwy"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpqu5hj7"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 33, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 8, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": true
, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "ap
i_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 8, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpqdnf0t"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp1xxkty"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 36, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 10, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": tru
e, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "a
pi_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 10, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp40s_zx"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmp2wpkts"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpz7sjxn"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 37, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 10, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": tru
e, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "a
pi_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 10, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpjsgbrs"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmppsjb96"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmptgx6w7"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 41, "target_temperature": 180, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 0, "filament_extruded": 0, "progress": 13, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 2164, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "initial_heating", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": false, "can_print_again": tru
e, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "a
pi_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 0, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 13, "name": "initial_heating"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpzfhv0b"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-l9Mfi9\\tmpxbxy6y"}, "jsonrpc": "2.0", "method": "camera_frame"}
