{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 227, "target_temperature": 230, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": ["load_filament", "unload_filament", "suspend"], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 210, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1953, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "printing", "extrusion_distance_b_mm": 0.0, "error": null, "
cancelled": false, "can_print_again": true, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profi
le_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 210, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 16, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 210, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"id":12,"jsonrpc":"2.0","method":"request_camera_stream","params":{"machine_name":"23C1:0005:23C100053C7059002409","path":"C:/Users/Rob/AppData/Local/Temp/MakerWare-zxPK5t"}}

{"jsonrpc": "2.0", "result": true, "id": 12}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpss6hwz"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 227, "target_temperature": 230, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": ["load_filament", "unload_filament", "suspend"], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 212, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1951, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "printing", "extrusion_distance_b_mm": 0.0, "error": null, "
cancelled": false, "can_print_again": true, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profi
le_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 212, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 212, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmp6ab_mj"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmppeqmwt"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpmi1mjr"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 227, "target_temperature": 230, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": ["load_filament", "unload_filament", "suspend"], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 213, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1950, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "printing", "extrusion_distance_b_mm": 0.0, "error": null, "
cancelled": false, "can_print_again": true, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profi
le_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 213, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 213, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpzj7hkr"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpcomnsv"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpm4lwhy"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 227, "target_temperature": 230, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": ["load_filament", "unload_filament", "suspend"], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 215, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1948, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "printing", "extrusion_distance_b_mm": 0.0, "error": null, "
cancelled": false, "can_print_again": true, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profi
le_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 215, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 215, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpz1h3yf"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmptjzimd"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpigvzeo"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 227, "target_temperature": 230, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": ["load_filament", "unload_filament", "suspend"], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 216, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1947, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "printing", "extrusion_distance_b_mm": 0.0, "error": null, "
cancelled": false, "can_print_again": true, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profi
le_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 216, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 216, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpv4jilm"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpru9gbd"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpy_mjgc"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 227, "target_temperature": 230, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": ["load_filament", "unload_filament", "suspend"], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 218, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1945, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "printing", "extrusion_distance_b_mm": 0.0, "error": null, "
cancelled": false, "can_print_again": true, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profi
le_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 218, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 218, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpcolf0b"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpri5wp4"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"id":13,"jsonrpc":"2.0","method":"cancel_process","params":{"machine_name":"23C1:0005:23C100053C7059002409"}}

{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 227, "target_temperature": 230, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": ["load_filament", "unload_filament", "suspend"], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 219, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1944, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": true, "step": "printing", "extrusion_distance_b_mm": 0.0, "error": null, "
cancelled": false, "can_print_again": true, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profi
le_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 219, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 219, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"jsonrpc": "2.0", "result": null, "id": 13}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 227, "target_temperature": 230, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 220, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1944, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": false, "step": "cancelling", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": true, "can_print_again": true,
 "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "api
_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 220, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "printing"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 220, "state": "RUNNING", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "cancelling"}, "type": "PrintFromFileJob", "conclusion": null}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "pausable": true, "failure": null, "process_id": 36, "extrusion_mass_a_grams": 6.861020371111167, "id": 0, "name": "1 inch cube", "can_cancel": true, "profile_name": "Platypus", "elapsed_time": 220, "state": "STOPPED", "driver_name": "birdwing", "duration_s": 2164.294311553379, "progress": {"progress": 17, "name": "cancelling"}, "type": "PrintFromFileJob", "conclusion": "CANCELED"}, "jsonrpc": "2.0", "method": "jobchanged"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmprawkoz"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpaedhud"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 226, "target_temperature": 230, "preheating": true}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 220, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1944, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": false, "step": "cleaning_up", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": true, "can_print_again": true
, "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "ap
i_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpab0ymp"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpjscxdh"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpjnbpux"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 227, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 220, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1944, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": false, "step": "cleaning_up", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": true, "can_print_again": true,
 "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "api
_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpkrqaeu"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpuutrtw"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpyxdoib"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpbqk2li"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpbtgijy"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpegwrvu"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpbpn_kv"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpjugjoq"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpwm3jk2"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpknsjah"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpmjrnb_"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpzv5hjj"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpa4smhi"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpmazyn9"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpgo0xvj"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 226, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 220, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1944, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": false, "step": "cleaning_up", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": true, "can_print_again": true,
 "extrusion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "api
_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpdgi2fk"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpdzxmhk"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 225, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": {"methods": [], "thing_id": null, "id": 36, "filepath": "/home/current_thing/1 inch cube.makerbot", "elapsed_time": 220, "filament_extruded": 1, "progress": 17, "username": "RobListon", "print_temperatures": {"1": 230, "0": 230}, "complete": false, "start_time": null, "time_remaining": 1944, "reason": null, "time_estimation": 2164.294311553379, "extrusion_mass_a_grams": 6.861020371111167, "extrusion_mass_b_grams": 0.0, "name": "PrintProcess", "cancellable": false, "step": "done", "extrusion_distance_b_mm": 0.0, "error": null, "cancelled": true, "can_print_again": true, "extru
sion_distance_a_mm": 2248.695286375979}, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "api_versio
n": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 225, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "RUNNING", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 225, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpaae6e9"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpukovxh"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpiqbrba"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpgqvgyp"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmp20_8gx"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpqysfz_"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 224, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpuqp4gt"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-zxPK5t\\tmpbmp2vg"}, "jsonrpc": "2.0", "method": "camera_frame"}
