{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 159, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 157, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 156, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"id":17,"jsonrpc":"2.0","method":"network_state","params":{"machine_name":"23C1:0005:23C100053C7059002409"}}

{"id":18,"jsonrpc":"2.0","method":"has_z_calibration_routine","params":{"machine_name":"23C1:0005:23C100053C7059002409"}}

{"id":19,"jsonrpc":"2.0","method":"get_available_z_offset_adjustment","params":{"machine_name":"23C1:0005:23C100053C7059002409"}}

{"id":20,"jsonrpc":"2.0","method":"get_sound_state","params":{"machine_name":"23C1:0005:23C100053C7059002409"}}

{"jsonrpc": "2.0", "result": {"state": "offline", "wifi": "disabled"}, "id": 17}
{"jsonrpc": "2.0", "result": false, "id": 18}
{"jsonrpc": "2.0", "result": 0.4, "id": 19}
{"id":21,"jsonrpc":"2.0","method":"get_z_adjusted_offset","params":{"machine_name":"23C1:0005:23C100053C7059002409"}}

{"jsonrpc": "2.0", "result": true, "id": 20}
{"jsonrpc": "2.0", "result": -0.1600000113248825, "id": 21}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 154, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 153, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 152, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 151, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": true, "tool_id": 7, "tool_present": true, "current_temperature": 150, "target_temperature": 0, "preheating": false}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 5, 0, 206], "current_process": null, "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.1.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
