{"id":7,"jsonrpc":"2.0","method":"request_camera_stream","params":{"machine_name":"23C1:0005:23C100053C7059002409","path":"C:/Users/Rob/AppData/Local/Temp/MakerWare-bE7tFd"}}

{"jsonrpc": "2.0", "result": true, "id": 7}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-bE7tFd\\tmp33m5gu"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": false, "preheating": false, "tool_present": true, "current_temperature": 27, "tool_id": 4, "target_temperature": 0}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 4, 0, 188], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.0.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-bE7tFd\\tmpds8omu"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-bE7tFd\\tmpwzrjlv"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-bE7tFd\\tmp9tuzqe"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"compatible_firmware": false, "has_been_connected_to": false, "platform_temperature": null, "has_heated_platform": false, "toolheads": {"extruder": [{"index": 0, "filament_presence": false, "preheating": false, "tool_present": true, "current_temperature": 26, "tool_id": 4, "target_temperature": 0}]}, "number_of_toolheads": 1, "can_print": true, "printer_type": "Platypus", "firmware_version": [1, 4, 0, 188], "toolhead_temperature": null, "connection_type": "offline", "toolhead_target_temperature": null, "display_name": "Replicator 6", "name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "disabled_errors": ["filament_slip"], "driver_name": "birdwing", "build_volume": [252, 199, 150], "state": "IDLE", "profile_name": "Platypus", "online": false, "api_version": "1.0.0"}, "jsonrpc": "2.0", "method": "machine_state_changed"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-bE7tFd\\tmpbo9man"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-bE7tFd\\tmpnzv1gl"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-bE7tFd\\tmp58aub8"}, "jsonrpc": "2.0", "method": "camera_frame"}
{"params": {"machine_name": {"iserial": "23C100053C7059002409", "pid": 5, "port_type": "UsbPort", "vid": 9153}, "file_path": "C:\\Users\\Rob\\AppData\\Local\\Temp\\MakerWare-bE7tFd\\tmplbgkyb"}, "jsonrpc": "2.0", "method": "camera_frame"}
